### ISSUE TITLE
Color to identify the rooms far away

### ISSUE THREAD

**Issue by ctselin** [dschipperCuningham/DynamoAdjacencyAnalysis#2]
Hi Dustin, 
First of all, I would like to say this is an awesome and smart script! I really love it. 
I got a question when I do some testing, I notice that the room color will change base on the distance of rooms from your video.
(https://cuningham.com/2020/03/30/how-much-walking-too-much-walking)
I didn't see that function in your script, even though I can copy the information from path line to rooms to achieve that. But I still curious what's your original idea to showing the room color? thank you! 

Chung

**Comment by schippdust** [comment]
Hi Chung,

Thanks for the question!  The color coding in the video was achieved using a view filter in Revit.  While you could use Dynamo to apply the colors via a material, this can get awkward as you populate the materials with a bunch of different colors. (Edit: I misspoke, it actually wouldn't work in this case to apply materials, as rooms don't have a material parameter)

I'm not sure if you've worked with view filters before, but you can find some general information about them here https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/Revit-DocumentPresent/files/GUID-145815E2-5699-40FE-A358-FFC739DB7C46-htm.html and plenty of tutorials on Youtube

Dustin

**Comment by ctselin** [comment]
Thank you Dustin,
Did you filter out the room or travel path? I assume the room, but which
data you filter out to show the color? One of the two added parameters is
by group and another one is empty but the start room. Thank you for the
answer and reference.

Chung

**Comment by schippdust** [comment]
Hi Chung,

Yes I filtered the rooms.  When you run the script it asks you to set a "Parameter Name for Analysis Output".  This should be a number parameter, and I would suggest creating it as a project parameter (a little more detail on this in the ReadMe file).  The script should (if everything is working properly) record the shortest distance out of all the distances to this parameter once it has run.  It will only record this parameter for the Start rooms, not for the Destination rooms.  You can use this output parameter to color code the rooms with the filter.

Dustin

**Comment by ctselin** [comment]
I know where my problem is.
I set the nurse station as the start room and the patient room as the
Destination room. It should be the opposite! Thank you for your time!
Awesome script!

Chung
